# Generated by Django 2.0.9 on 2018-11-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arrendatario',
        ),
        migrations.RemoveField(
            model_name='ciudadano_comuna',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='cliente_banco',
            name='banco',
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='Ciudadano_Comuna',
        ),
        migrations.DeleteModel(
            name='Cliente_banco',
        ),
        migrations.DeleteModel(
            name='Comuna',
        ),
    ]
